# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      '**'
  pull_request:
    branches:
      '**'
env:
  GHACTIONS: ACTIVE

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          scripts/install
      - name: Install spaCy model
        run: |
          python -m spacy download en_core_web_sm
      - name: Download NLTK stopwords
        run: |
          python -m nltk.downloader stopwords, punkt
      - name: Run Python Script
        run: |
          python eventseries/src/main/main.py
      - name: Run tests
        run: |
          scripts/test